name: Terraform Apply & Deploy to Azure App Service

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Zip App
        run: |
          mkdir output
          cd simple_app
          zip -r ../output/app.zip .

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-policy-demo
          slot-name: production
          package: output/app.zip
