name: Terraform Deploy to Azure

on:
  push:
    branches:
      - main

env:
  TF_VAR_azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Remove API resource from state
        run: terraform state rm azurerm_api_management_api.api || echo "Resource not in state, skipping"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
