name: Terraform Apply & Deploy to Azure App Service

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Wait for App Service to be ready
        run: |
          for i in {1..10}; do
            echo "Checking if app-policy-demo is available..."
            if az webapp show --name app-policy-demo --resource-group rg-demo-policy &> /dev/null; then
              echo "App found!"
              break
            fi
            echo "App not found yet, retrying in 10 seconds..."
            sleep 10
          done

      - name: Zip the app
        run: |
          mkdir output
          cd simple_app
          zip -r ../output/app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-policy-demo
          slot-name: production
          package: output/app.zip
